export const wData = [{
    "id": 0,
    "title": "ROLL!!",
    "description": "Browser-based pixel art dice roller",
    "tags": ["development", "pixel art"],
    "thumbnail": "/roll_cover.PNG",
    "endpoint": "/works/roll",
    "modal": "",
    "spread": []
},

{
    "id": 1,

    "title": "plant 300!",
    "description": "A poetry chapbook for romantics",
    "tags": ["writing", "poetry"],
    "thumbnail": "/plant300/plant300cover.PNG",
    "endpoint": "",
    "modal": "plant300",
    "spread": ["plant300/plant300cover.png",
        "plant300/plant300backcover.png",
        "plant300/plant300plate.png",
        "plant300/plant300_01.png",
        "plant300/plant300_02.png",
        "plant300/plant300_03.png",
        "plant300/plant300_04.png",
        "plant300/plant300_05.png",
        "plant300/plant300_06.png",
        "plant300/plant300_07.png",
        "plant300/plant300_08.png",
        "plant300/plant300_09.png",
        "plant300/plant300_10.png",
        "plant300/plant300_11.png",
        "plant300/plant300_12.png",
        "plant300/plant300_13.png",
        "plant300/plant300_14.png",
        "plant300/plant300_15.png",
        "plant300/plant300_16.png",
        "plant300/plant300_17.png",
        "plant300/plant300_18.png",
        "plant300/plant300_19.png",
        "plant300/plant300_20.png",
    ]
},

{
    "id": 2,

    "title": "jream",
    "description": "Lightweight dream journal",
    "tags": ["development", "react", "javascript"],
    "thumbnail": "",
    "endpoint": "/works/jream",
    "modal": "",
    "spread": []
},

{
    "id": 3,

    "title": "B12",
    "description": "A poetry chapbook for social climbers",
    "tags": ["writing", "poetry"],
    "thumbnail": "/b12/b12cover.PNG",
    "endpoint": "",
    "modal": "b12",
    "spread": ["b12/b12cover.png",
        "b12/b12backcover.png",
        "b12/b12plate.png",
        "b12/b12_01.png",
        "b12/b12_02.png",
        "b12/b12_03.png",
        "b12/b12_04.png",
        "b12/b12_05.png",
        "b12/b12_06.png",
        "b12/b12_07.png",
        "b12/b12_08.png",
        "b12/b12_09.png",
        "b12/b12_10.png",
        "b12/b12_11.png",
        "b12/b12_12.png",
        "b12/b12_13.png",
        "b12/b12_14.png",
        "b12/b12_15.png",
        "b12/b12_16.png",
        "b12/b12_17.png",
        "b12/b12_18.png",
        "b12/b12_19.png",
    ]
},

{
    "id": 4,

    "title": "Best Delegate",
    "description": "A poetry chapbook for high performers",
    "tags": ["writing", "poetry"],
    "thumbnail": "/bestdelegate/bestdelegatecover.PNG",
    "endpoint": "",
    "modal": "bestdelegate",
    "spread": ["bestdelegate/bestdelegatecover.png",
        "bestdelegate/bestdelegatebackcover.png",
        "bestdelegate/bestdelegateplate.png",
        "bestdelegate/bestdelegate_01.png",
        "bestdelegate/bestdelegate_02.png",
        "bestdelegate/bestdelegate_03.png",
        "bestdelegate/bestdelegate_04.png",
        "bestdelegate/bestdelegate_05.png",
        "bestdelegate/bestdelegate_06.png",
        "bestdelegate/bestdelegate_07.png",
        "bestdelegate/bestdelegate_08.png",
        "bestdelegate/bestdelegate_09.png",
        "bestdelegate/bestdelegate_10.png",
        "bestdelegate/bestdelegate_11.png",
        "bestdelegate/bestdelegate_12.png",
        "bestdelegate/bestdelegate_13.png",
        "bestdelegate/bestdelegate_14.png",
        "bestdelegate/bestdelegate_15.png",
        "bestdelegate/bestdelegate_16.png",
        "bestdelegate/bestdelegate_17.png",
        "bestdelegate/bestdelegate_18.png",
        "bestdelegate/bestdelegate_19.png",
    ]
},
]

    export const writingData = wData.filter(item => item.tags.includes("writing"));
    export const devData = wData.filter(item => item.tags.includes("development"));